version: 2.1

jobs:
  deploy-service:
    docker:
      - image: circleci/node:12.10
    parameters:
      service_path:
        type: string
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "<< parameters.service_path >>/package-lock.json" }}
            - dependencies-cache

      - run:
          name: Install Serverless CLI
          command: sudo npm i -g serverless

      - run:
          name: Install dependencies
          command: |
            cd << parameters.service_path >>
            npm install

      - run:
          name: Unit test application
          no_output_timeout: 20m
          command: |
            cd << parameters.service_path >>
            npm test

      - run:
          name: Deploy application
          no_output_timeout: 20m
          command: |
            cd << parameters.service_path >>
            serverless deploy -v

      - save_cache:
          paths:
            - node_modules
            - << parameters.service_path >>/node_modules
          key: dependencies-cache-{{ checksum "<< parameters.service_path >>/package-lock.json" }}

workflows:
  build-deploy:
    jobs:
      - deploy-service:
          name: Deploy Todos Serverless App
          service_path: backend
          context: Development
