version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  deploy-web:
    docker:
      - image: circleci/node:12.10
    parameters:
      service_path:
        type: string
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "<< parameters.service_path >>/package-lock.json" }}
            - dependencies-cache

      - run:
          name: Install dependencies
          command: |
            cd << parameters.service_path >>
            npm install

      - run:
          name: Linting
          command: |
            cd << parameters.service_path >>
            npm run lint

      - run:
          name: Unit testing
          command: |
            cd << parameters.service_path >>
            npm test

      - run:
          name: Build production artifacts
          command: |
            cd << parameters.service_path >>
            npm run build
            ls -la build

      - aws-s3/sync:
          from: << parameters.service_path >>/build
          overwrite: true
          to: 's3://my-cloud-dev-s3'

      - save_cache:
          paths:
            - << parameters.service_path >>/node_modules
          key: dependencies-cache-{{ checksum "<< parameters.service_path >>/package-lock.json" }}

  deploy-service:
    docker:
      - image: circleci/node:12.10
    parameters:
      service_path:
        type: string
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "<< parameters.service_path >>/package-lock.json" }}
            - dependencies-cache

      - run:
          name: Install Serverless CLI
          command: sudo npm i -g serverless

      - run:
          name: Install dependencies
          command: |
            cd << parameters.service_path >>
            npm install

      - run:
          name: Unit test application
          no_output_timeout: 20m
          command: |
            cd << parameters.service_path >>
            npm test

      - run:
          name: Deploy application
          no_output_timeout: 20m
          command: |
            cd << parameters.service_path >>
            serverless deploy -v

      - save_cache:
          paths:
            - << parameters.service_path >>/node_modules
          key: dependencies-cache-{{ checksum "<< parameters.service_path >>/package-lock.json" }}

workflows:
  build-deploy:
    jobs:
      - deploy-web:
          name: Deploy Todos React App
          service_path: client
          context: Development
      - deploy-service:
          name: Deploy Todos Serverless App
          service_path: backend
          context: Development
